server:
  port: 7007

spring:
  application:
    name: search-service
  elasticsearch:
    rest:
      uris:
        - http://localhost:9200
#      读超时时间，单位 s
      read-timeout: 10
#      连接超时时间，单位 s
      connection-timeout: 5
  main:
#    可以重写？多个接口上的@FeignClient(“相同服务名”)会报错
    allow-bean-definition-overriding: true

  jackson:
#    配置json处理时忽略空值
    default-property-inclusion: non_null

  rabbitmq:
    host: 127.0.0.1
    virtual-host: /leyou
    username: leyou
    password: leyou


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
#      拉取服务时间
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10